---
- name: Build and run the ruby app
  hosts: postgres
  gather_facts: False

  vars:
    docker_env:
      DOCKER_HOST: "tcp://127.0.0.1:2375"

    pg_container: shoutouts_postgres
    pg_database: shoutouts
    pg_user: shoutouts_web
    pg_password: secret

    app_port: 5000
    app_src_path: ./ruby-app
    app_container: shoutouts_web
    app_docker_image: jbgo/shoutouts
    app_docker_image_tag: latest
    app_docker_links:
      - "{{pg_container}}:postgres"
    app_instances: 12

  roles:
    - { role: docker-postgres, tags: db }
